### ISSUE TITLE
Total wait skims contain all zeros

### ISSUE THREAD

**Issue by binnympaul** [CMAP-REPOS/cmap_abm#2]
Total wait skims are updated with all zeros due a typo on line 1010 in the transit assignment skimming macro:
"~+|1|y|mf"Pwa2%2%%y%"|n|(mf"Pwa2%2%%y%"-mf"Pwa2%2%%y%").max.0|||n|2"

**Comment by nmpeterson** [comment]
@binnympaul it looks like this old code was reintroduced with the most recent commit. Was that intentional, or should it be changed to `~+|1|y|mf"Pwa2%2%%y%"|n|(mf"Pwa2%2%%y%"-mf"Pwa1%2%%y%").max.0|||n|2` again?

**Comment by binnympaul** [comment]
@nmpeterson yes, please change it. To fix the issues we found with transit skimming, I started using an earlier version of the script but forgot to change this line.
