### ISSUE TITLE
add new UECs for PNR and KNR

### ISSUE THREAD

**Issue by bstabler** [CMAP-REPOS/cmap_abm#3]
need to commit UECs as well

**Comment by binnympaul** [comment]
New UECs committed with following changes:
1. Transit mode labels - PlaceHolderMode, WalkTransit, KNR, PNR
2. All DL and DP labels updated with KNR and PNR.
3. Redundant constants were removed
4. Coefficients corresponding to placeholder mode (previously Walk Local) were removed.
